-- ============================================================================
-- ENTERPRISE SECURITY SHIELD - Database Schema (PostgreSQL 17)
-- ============================================================================
--
-- PURPOSE: Persistent storage for security events, bans, and threat scores
--
-- TABLE NAMING: All tables use 'security_shield_' prefix for namespace isolation
--
-- DUAL-WRITE ARCHITECTURE:
-- - Redis: L1 cache (sub-millisecond reads, volatile)
-- - PostgreSQL: Persistent storage (survives restarts, auditing, compliance)
--
-- PERFORMANCE OPTIMIZATIONS:
-- - Composite indexes for common queries
-- - JSONB for flexible event data
-- - Automatic cleanup via retention policies
-- - Hot path queries use Redis (ban checks, rate limits)
-- - Cold path queries use DB (reporting, analytics, compliance)
--
-- COMPATIBILITY: PostgreSQL 9.5+ (JSONB support required)
-- ============================================================================

-- NOTE: This schema is for reference only.
-- The actual tables are created by the migrations in:
--   database/migrations/postgresql/001_create_security_tables.sql
--   database/migrations/mysql/001_create_security_tables.sql

-- ============================================================================
-- TABLES CREATED BY MIGRATIONS:
-- ============================================================================
--
-- 1. security_shield_events      - Audit log of all security events
-- 2. security_shield_bans        - IP bans with expiration
-- 3. security_shield_whitelist   - IP whitelist
-- 4. security_shield_config      - Security configuration key/value store
-- 5. security_shield_scores      - Threat scores per IP
-- 6. security_shield_request_counts - Rate limiting counters
-- 7. security_shield_bot_cache   - Bot verification cache
-- 8. security_shield_rate_limits - Atomic rate limit counters
--
-- ============================================================================
-- DEPLOYMENT NOTES
-- ============================================================================
--
-- 1. Run migrations via installer:
--    php vendor/ados-labs/enterprise-admin-panel/elf/install.php
--
-- 2. Or run migrations manually:
--    psql -U your_user -d your_db -f database/migrations/postgresql/001_create_security_tables.sql
--
-- 3. Configure DatabaseStorage with PDO:
--    $pdo = new PDO('pgsql:host=localhost;dbname=security_db', 'user', 'password');
--    $storage = new DatabaseStorage($pdo, $redis);
--
-- 4. Setup cron jobs for cleanup (see migrations for cleanup function)
--
-- ============================================================================
